### ISSUE TITLE
Display of monthly graph data is not sorted?

### ISSUE THREAD

**Issue by rngadam** [coderbunker/timesheet-dashboard-react#8]
After an update to the latest data, I'm getting months in seemingly random order:

<img width="1010" alt="screen shot 2018-07-22 at 6 10 17 pm" src="https://user-images.githubusercontent.com/538542/43044554-87a8f3c0-8dda-11e8-897e-70bf58d03866.png">

Maybe the GraphQL is missing an orderBy and the code is assuming the data is in order?

The data appears correctly in https://data.coderbunker.com

**Comment by sam123evers** [comment]
Fixed this by adding 
``(orderBy: [ENTRY_YEAR_DESC, ENTRY_MONTH_DESC])``
to the ``allMonthyGrosses`` query

How is looks now on my local machine:

![screen shot 2018-07-24 at 5 40 11 pm](https://user-images.githubusercontent.com/25334488/43130184-b3d07182-8f68-11e8-91df-11c7138405f4.png)

**Comment by sam123evers** [comment]
Hoping to get a reminder about how to make the production build live on dashboard.coderbunker.com

**Comment by rngadam** [comment]
Did you break the current release? 

<img width="897" alt="screen shot 2018-07-26 at 2 49 51 pm" src="https://user-images.githubusercontent.com/538542/43246112-30ddf016-90e3-11e8-99b4-abc3c1210d2c.png">

Where's the pull request for this fix?

Why is there a PR on this repo that wasn't reviewed/merged first?

https://github.com/coderbunker/timesheet-dashboard-react/pull/7

**Comment by rngadam** [comment]
You pushed the whole master branch to gh-pages instead of just the public subdirectory which is why it broke. 

That's also why you need a README.md in your projects with deployment instruction

**Comment by sam123evers** [comment]
Last time I did this I created a production build and deployed it
I'm assuming I should repeat this process again to get is working?
https://codeburst.io/deploy-react-to-github-pages-to-create-an-amazing-website-42d8b09cd4d
article of steps I took was given to my by alex
essentially on local gh-pages branch, running npm run build and then npm run deploy

**Comment by sam123evers** [comment]
Ok so running those commands brought the site back online but did not incorporate the orderBy fix

please advise

**Comment by sam123evers** [comment]
![screen shot 2018-07-26 at 3 09 12 pm](https://user-images.githubusercontent.com/25334488/43246987-f08dd30c-90e5-11e8-8fef-4901ff0ed6b5.png)

**Comment by sam123evers** [comment]
oh wait I guess it worked
dashboard.coderbunker.com

**Comment by rngadam** [comment]
did you pull first?

**Comment by rngadam** [comment]
You had forgotten the part where you need to push the subdirectory, not the root. I just did.

document the other build steps in the README.md

You forgot the part where you need to push the subdirectory, not the root. I just did.

document the other build steps in the README.md

Fixed: 

<img width="1195" alt="screen shot 2018-07-26 at 3 13 06 pm" src="https://user-images.githubusercontent.com/538542/43247172-7f201d78-90e6-11e8-8082-3faf68bf8a3e.png">

**Comment by rngadam** [comment]
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/
